name: 'Project Factory'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/project-definitions/**.tfvars'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan-and-request-approval:
    name: 'Terraform Plan & Request Approval'
    runs-on: ubuntu-latest
    outputs:
      tf_workspace: ${{ steps.prepare_vars.outputs.workspace_name }}
      tf_var_file: ${{ steps.prepare_vars.outputs.var_file }}
      tf_plan_artifact: 'tfplan-${{ steps.prepare_vars.outputs.workspace_name }}'
      pr_number: ${{ github.event.pull_request.number }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Detect File and Prepare Variables'
        id: prepare_vars
        run: |
          echo "Comparando (BASE) ${{ github.event.pull_request.base.sha }} con (HEAD) ${{ github.event.pull_request.head.sha }}"
          changed_file=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep 'terraform/project-definitions/.*\.tfvars$' | head -n 1)

          if [[ -z "$changed_file" ]]; then
            echo "Error: No se encontró ningún fichero .tfvars modificado en esta PR."
            exit 1
          fi
          
          # Extraemos el nombre del proyecto del fichero para usarlo como nombre del workspace
          PROJECT_NAME=$(grep -oP 'project_name\s*=\s*"\K[^"]+' $changed_file)
          if [[ -z "$PROJECT_NAME" ]]; then
            echo "Error: No se pudo extraer project_name del fichero .tfvars"
            exit 1
          fi
          echo "✅ Nombre del proyecto para workspace: $PROJECT_NAME"
          
          # Preparamos la ruta relativa del fichero de variables
          relative_path=$(echo "$changed_file" | sed 's|^terraform/||')
          echo "✅ Ruta relativa para Terraform: $relative_path"
          
          # Usamos GITHUB_OUTPUT para pasar valores a otros steps y jobs
          echo "workspace_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "var_file=$relative_path" >> $GITHUB_OUTPUT
          echo "artifact_name=tfplan-$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
      
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}"
        working-directory: ./terraform


      # crear o seleccionar el workspace
      - name: 'Select or Create Terraform Workspace'
        run: terraform workspace select ${{ steps.prepare_vars.outputs.workspace_name }} || terraform workspace new ${{ steps.prepare_vars.outputs.workspace_name }}
        working-directory: ./terraform

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./terraform

      - name: 'Terraform Plan'
        id: plan
        working-directory: ./terraform

        run: |
          terraform plan \
            -var-file="${{ steps.prepare_vars.outputs.var_file }}" \
            -out=tfplan \
            -no-color
        env:
          TF_VAR_billing_account: ${{ secrets.TF_VAR_billing_account }}
        continue-on-error: true

      - name: 'Publish Plan to PR'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            #### Terraform Plan 📖
            * **Proyecto (Workspace):** \`${{ steps.prepare_vars.outputs.workspace_name }}\`
            * **Fichero de definición:** \`${{ steps.prepare_vars.outputs.var_file }}\`
            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            **Acción Requerida:** Un revisor debe [aprobar el despliegue](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) para continuar con el \`apply\`.
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: 'Exit with error if plan failed'
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: 'Upload Plan Artifact'
        uses: actions/upload-artifact@v4
        with:
          # El nombre del artefacto ahora es dinámico para evitar colisiones
          name: ${{ steps.prepare_vars.outputs.artifact_name }}
          path: terraform/tfplan

  apply-approved-plan:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: plan-and-request-approval

    environment: 'project-approval'
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}"
      
      # selecionar el mismo workspace usando la salida del job anterior
      - name: 'Select Workspace'
        run: terraform workspace select ${{ needs.plan-and-request-approval.outputs.tf_workspace }}
      
      - name: 'Download Plan Artifact'
        uses: actions/download-artifact@v4
        with:
          # descargar el artefacto con el nombre dinámico que nos pasa el job anterior
          name: ${{ needs.plan-and-request-approval.outputs.tf_plan_artifact }}
          path: terraform/

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan

      - name: 'Get Terraform Outputs'
        id: get_outputs
        working-directory: ./terraform
        run: terraform output -json

      - name: 'Publish Outputs to PR'
        uses: actions/github-script@v7
        env:
          JSON_OUTPUTS: ${{ steps.get_outputs.outputs.stdout }}
        with:
          script: |
            const outputs = JSON.parse(process.env.JSON_OUTPUTS);
            
            let body = '###  Despliegue Completado - Outputs del Proyecto\n\n';
            
            if (Object.keys(outputs).length === 0) {
              body += 'No se generaron outputs.';
            } else {
              body += '| Nombre | Valor |\n';
              body += '|--------|-------|\n';
              
              for (const key in outputs) {
                const output = outputs[key];
                const displayValue = output.sensitive ? '(sensitive)' : JSON.stringify(output.value);
                body += `| ${key} | \`\`\`${displayValue}\`\`\` |\n`;
              }
            }
            github.rest.issues.createComment({
              issue_number: ${{ needs.plan-and-request-approval.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });